# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msgfilter.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import service as _service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='msgfilter.proto',
  package='',
  serialized_pb='\n\x0fmsgfilter.proto\"-\n\x10MsgFilterRequest\x12\x0c\n\x04type\x18\x01 \x02(\x05\x12\x0b\n\x03msg\x18\x02 \x02(\t\"B\n\x11MsgFilterResponse\x12\x12\n\nerror_code\x18\x01 \x02(\x05\x12\x0c\n\x04\x64\x65sc\x18\x02 \x02(\t\x12\x0b\n\x03ret\x18\x03 \x02(\x05\x32\x46\n\x10MsgFilterService\x12\x32\n\tMsgMethod\x12\x11.MsgFilterRequest\x1a\x12.MsgFilterResponseB\x03\x90\x01\x01')




_MSGFILTERREQUEST = _descriptor.Descriptor(
  name='MsgFilterRequest',
  full_name='MsgFilterRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='MsgFilterRequest.type', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='msg', full_name='MsgFilterRequest.msg', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=19,
  serialized_end=64,
)


_MSGFILTERRESPONSE = _descriptor.Descriptor(
  name='MsgFilterResponse',
  full_name='MsgFilterResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error_code', full_name='MsgFilterResponse.error_code', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='desc', full_name='MsgFilterResponse.desc', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ret', full_name='MsgFilterResponse.ret', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=66,
  serialized_end=132,
)

DESCRIPTOR.message_types_by_name['MsgFilterRequest'] = _MSGFILTERREQUEST
DESCRIPTOR.message_types_by_name['MsgFilterResponse'] = _MSGFILTERRESPONSE

class MsgFilterRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MSGFILTERREQUEST

  # @@protoc_insertion_point(class_scope:MsgFilterRequest)

class MsgFilterResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MSGFILTERRESPONSE

  # @@protoc_insertion_point(class_scope:MsgFilterResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\220\001\001')

_MSGFILTERSERVICE = _descriptor.ServiceDescriptor(
  name='MsgFilterService',
  full_name='MsgFilterService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=134,
  serialized_end=204,
  methods=[
  _descriptor.MethodDescriptor(
    name='MsgMethod',
    full_name='MsgFilterService.MsgMethod',
    index=0,
    containing_service=None,
    input_type=_MSGFILTERREQUEST,
    output_type=_MSGFILTERRESPONSE,
    options=None,
  ),
])

class MsgFilterService(_service.Service):
  __metaclass__ = service_reflection.GeneratedServiceType
  DESCRIPTOR = _MSGFILTERSERVICE
class MsgFilterService_Stub(MsgFilterService):
  __metaclass__ = service_reflection.GeneratedServiceStubType
  DESCRIPTOR = _MSGFILTERSERVICE

# @@protoc_insertion_point(module_scope)
